### ISSUE TITLE
1. User @GetMapping and @Post mapping instead of @RequestMapping for methods 2. Move common prefix (i.e. `/comment`) to a class level

### ISSUE THREAD

**Issue by zozich** [Romik9/Final_Project#43]
https://github.com/Romik9/Final_Project/blob/1869c314faea6d2b5a0c94cdf75d93487777a62b/src/main/java/ua/danit/final_project/controllers/CommentController.java#L23

https://github.com/Romik9/Final_Project/blob/1869c314faea6d2b5a0c94cdf75d93487777a62b/src/main/java/ua/danit/final_project/controllers/CommentController.java#L29

**Comment by warfawl** [comment]
Resolved: https://github.com/Romik9/Final_Project/pull/60
