### ISSUE TITLE
Use @GetMapping and @PostMapping annotations instead of @RequestMapping on method level

### ISSUE THREAD

**Issue by zozich** [Romik9/Final_Project#44]
https://github.com/Romik9/Final_Project/blob/1869c314faea6d2b5a0c94cdf75d93487777a62b/src/main/java/ua/danit/final_project/controllers/RoleController.java#L22

https://github.com/Romik9/Final_Project/blob/1869c314faea6d2b5a0c94cdf75d93487777a62b/src/main/java/ua/danit/final_project/controllers/RoleController.java#L27

**Comment by warfawl** [comment]
resolved: `https://github.com/Romik9/Final_Project/pull/60`
